### ISSUE TITLE
TypeError:: isAllowed type hint string no allowed Nette\Security\IAuthorizator::ALL

### ISSUE THREAD

**Issue by duskohu** [Arachne/Security#2]
when I use 
`->isAllowed('resource', Nette\Security\IAuthorizator::ALL);`
I have TypeError:: isAllowed() must be of the type string, null given
https://github.com/Arachne/Security/blob/v0.4.0/src/Authorization/AuthorizatorInterface.php#L17
https://github.com/nette/security/blob/v2.4.2/src/Security/IAuthorizator.php#L18

**Comment by enumag** [comment]
Ups, looks like I missed that. Can you change the typehint to `?string`? PHP 7.1 is already required anyway.

**Comment by enumag** [comment]
After reconsidering I've reverted the change. It doesn't make much sense to ask if someone has all privileges on a resource. You should add another more specific privilege instead.
