### ISSUE TITLE
Incompatibility with Nette\Presenter store/restore request

### ISSUE THREAD

**Issue by josefsabl** [Arachne/Security#6]
Is it possible that the entity loader is not compatible with the Nette Presenter's store/restore request? Looks like request now contains whole documents (that can have closures in them) and I get Serialization of  'Closure' is not allowed error. Any idea what to do with this. I guess that: Do not use storeRequest will fix that :-)

**Comment by enumag** [comment]
See the [EntityLoaderPresenterTrait](https://github.com/Arachne/EntityLoader/blob/master/src/Application/EntityLoaderPresenterTrait.php). If you have any problem with it, create an issue in the Arachne/EntityLoader repository, not here.
