### ISSUE TITLE
Each subsequent isAllowed call PermissionAuthorizator adds new __authenticated role.

### ISSUE THREAD

**Issue by josefsabl** [Arachne/Security#8]
Pull request here:

https://github.com/Arachne/Security/pull/7

**Comment by enumag** [comment]
The `$roles` with `'__authenticated'` should never be written back to `Identity`. How did that happen?

**Comment by josefsabl** [comment]
Ok, probably something wrong on my side. I will take look at it.

**Comment by josefsabl** [comment]
I confirm this was a bug on our side. We were passing roles from our data object to identity as a reference (sort of).
